### ISSUE TITLE
Add table with Id and email properties

### ISSUE THREAD

**Issue by DanielLyubin** [TechnionYearlyProject/Cognitivity#129]
I need a table that has an ID as primary key and email as the second column, services and controllers for adding/removing emails

**Comment by ophirKatz** [comment]
Dont know anything about the db

**Comment by DanielLyubin** [comment]
Also need a service to get the id of the email

**Comment by DanielLyubin** [comment]
Add DAOs for this table @guyshe

**Comment by ophirKatz** [comment]
Changed TestManager to have only email
