### ISSUE TITLE
Add image storing and fetching support in Spring MVC

### ISSUE THREAD

**Issue by DanielLyubin** [TechnionYearlyProject/Cognitivity#175]
Storing images in SQL is bad practice, so we need to store images in the server's file system or an external storage service (our Firebase?). For storing on file system there's this thread: https://stackoverflow.com/questions/41399155/storing-images-in-a-directory-spring-mvc

Est. Time:  6 Hours

**Comment by DanielLyubin** [comment]
Using firebase's storage is less error prone and seems to be simpler than implementing ourselves.
API: https://firebase.google.com/docs/storage/web/start?authuser=0
Est. time is still 6 hrs

**Comment by Peer-Sagiv** [comment]
Expected time - 4 hours

**Comment by Peer-Sagiv** [comment]
Actual time - 5 hours.
Additional information for extra development can be found in issues:
#268 #269 #270 #271
