### ISSUE TITLE
Bug in service tests - Error outputs

### ISSUE THREAD

**Issue by ophirKatz** [TechnionYearlyProject/Cognitivity#177]
When running the service tests, they pass now, but all of the have empty error messages from the logger

**Comment by Peer-Sagiv** [comment]
The problem was caused by misinterpretation of the logger messages on testing.
Since the tests check error handling, these messages are thrown, and they are integral parts pf the tests themselves.

**Comment by Peer-Sagiv** [comment]
Estimated time - 0.5 hour
Actual time - 0.5 hour
