### ISSUE TITLE
define fields for question's and block's tags arrays

### ISSUE THREAD

**Issue by BenHunter101** [TechnionYearlyProject/Cognitivity#202]
we need to make sure the tags are supported in the backend (array of strings)

**Comment by ophirKatz** [comment]
@BenHunter101 We have only one tag for blocks at this moment. why do we need more? (array of tags)

**Comment by ophirKatz** [comment]
@Peer-Sagiv could you define it? not sure how to define arrays in mysql

**Comment by ophirKatz** [comment]
done
