### ISSUE TITLE
Change subject table and dao properties

### ISSUE THREAD

**Issue by DanielLyubin** [TechnionYearlyProject/Cognitivity#210]
The current properties are name, IP address and browser. I don't think it's a good idea to save IP address.
Maybe we should save properties as requested in the registration form: name, birthdate, ID, occupation, martial status and browser

**Comment by Peer-Sagiv** [comment]
Estimated time: 2.5 hours

**Comment by Peer-Sagiv** [comment]
Base additions were made.
However, in order to give them meaning, an API by the front end (@DanielLyubin ) must be provided for further work.

**Comment by Peer-Sagiv** [comment]
Waiting for more requests about desired API. As of now, all requirements are met, therefore I close this issue.
