### ISSUE TITLE
Add checks for input correctness when uploading a file

### ISSUE THREAD

**Issue by Peer-Sagiv** [TechnionYearlyProject/Cognitivity#229]
As of now, whenever a files is uploaded to a test loader, the test loader tries to parse it even if it's not a valid test files. Because of that several runtime exceptions are thrown that hold no information about the source of the problem.
In order to prevent this problem, and allow users to understand why their upload fails, some extra checks should be added.

**Comment by ophirKatz** [comment]
On it. approx time - 30 minutes.
