### ISSUE TITLE
Add support for Blocks and Questions tags in the DB side

### ISSUE THREAD

**Issue by BenHunter101** [TechnionYearlyProject/Cognitivity#232]
We need to define fields in the DB so we can pass the tags information from the front end. (same like "notes", "test name" etc..)

**Comment by Peer-Sagiv** [comment]
@BenHunter101 Can you define they required API from the backend? e.g required functions and information?

**Comment by ophirKatz** [comment]
Ben, tell us exactly what you need from us - which services, and to which end?
Support for tags already exists in the db (in the json representation).

**Comment by BenHunter101** [comment]
All good (: 
My bad
