### ISSUE TITLE
Gather errors to a single handling procedure

### ISSUE THREAD

**Issue by Peer-Sagiv** [TechnionYearlyProject/Cognitivity#245]
As of now, there's a message interceptor class for gathering all error messages from the back end.
The interceptor class is not fully functional, thus the front end still relays on the faulty design of checking each message for error while getting it.
The interceptor needs to be fixed and become fully functional, and when it does, all the error message handling from inside the message calls should be deleted.

**Comment by ophirKatz** [comment]
Whats with that? @Peer-Sagiv

**Comment by Peer-Sagiv** [comment]
Unfortunately since some of the services of the front end require some information about the reason for the error (For example, when creating or updating a test, the error code must be passed to the calling function itself), an injector cannot be implemented without a redesign of all the communication with the backend, rendering its creation useless.
