### ISSUE TITLE
GUI bugs Intifada #1 - Test creation -> question preview

### ISSUE THREAD

**Issue by BenHunter101** [TechnionYearlyProject/Cognitivity#251]
When changing answers in the multiple choice question, the confidence bar doesn't appear\disappear properly. 
The wanted state:
- When there's a marked answer - the confidence bar appears.
- When there isn't any marked answer - the confidence bar is hidden.

**Comment by guyshe** [comment]
Estimated time: 10 minutes
Actual time: 10 minutes
