### ISSUE TITLE
GUI bugs Intifada #4 - Drill down question

### ISSUE THREAD

**Issue by BenHunter101** [TechnionYearlyProject/Cognitivity#254]
Steps to bug reproduce:
1. In drill down question, enter a main answer that starts and ends with some character, fill the rest with spaces.

Although the spaces are trimmed when showing the answer, the bar still expands too much and messes up the UI a bit.

**Comment by guyshe** [comment]
Estimated time: 20 minutes
Actual time: 20 minutes
