### ISSUE TITLE
Update services to use the updated hibernate functions

### ISSUE THREAD

**Issue by guyshe** [TechnionYearlyProject/Cognitivity#262]
added more efficient functions for adding values to the db, need to update accordingly in the services
in CognitiveTestDAO: 
    - public long add(CognitiveTest cognitiveTest, Long testManagerId);
in TestAnswerDAO:
    - public long add(TestAnswer answer, Long testSubjectId, Long testQuestionId, Long cognitiveTestId);
in TestBlockDAO:
    - public long add(TestBlock testBlock, Long cognitiveTestId);
in TestQuestionDAO:
    - public long add(TestQuestion testQuestion, Long testBlockId, Long cognitiveTestId, Long testManagerId);

**Comment by Peer-Sagiv** [comment]
On it.
Estimated time - 1 hour

**Comment by ophirKatz** [comment]
Nope
