### ISSUE TITLE
Display all pictures in  the user upon choosing to upload a picture to a question

### ISSUE THREAD

**Issue by Peer-Sagiv** [TechnionYearlyProject/Cognitivity#271]
When a user wants to put pictures in a question, a simple display of all possible pictures should be put for him to choose from.

**Comment by Peer-Sagiv** [comment]
Estimated time - 2-3 hours

**Comment by Peer-Sagiv** [comment]
Done!
actual time - 3 hours

**Comment by guyshe** [comment]
we were there too!! 
@markerlich
