### ISSUE TITLE
Change param types in delete/find function controllers to ID of object

### ISSUE THREAD

**Issue by DanielLyubin** [TechnionYearlyProject/Cognitivity#84]
The current state of the controller's functions' parameters are objects. It is good only for updating/saving tests, but for deleting and finding is BAD, because in the client side the API of HTTP requests doesn't allow passing data (i.e as body of message) with GET or DELETE requests. I don't know if it was like that from the beginning or who tf changed it to objects but YOU NEED TO CHANGE IT TO ID ASAP

**Comment by Peer-Sagiv** [comment]
Solved on the last commit.
