### ISSUE TITLE
Expand DB to support different answer types

### ISSUE THREAD

**Issue by DanielLyubin** [TechnionYearlyProject/Cognitivity#89]
Current implementation supports a specific type of question, but it needs to support three types.
Please reference the objects' definition at client/src/app/models/index.ts to see what attributes the question object has (as well as rest of the objects in the file).

**Comment by DanielLyubin** [comment]
Ignore MultipleAnswerQuestion for now, we need to change it (@markerlich )

**Comment by ophirKatz** [comment]
fixed by having answer field to be string type, and json format will contain the actual question type's data
